import { SignedIn } from "@clerk/clerk-react";
import { SignInButton, SignedOut } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>CariKabel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-full flex-col items-center justify-center">
        <SignedOut>
          <SignInButton redirectUrl="/dashboard">
            <Button>Login</Button>
          </SignInButton>
        </SignedOut>
        <SignedIn>
          <Button asChild>
            <Link href="/dashboard">Go to dashboard</Link>
          </Button>
        </SignedIn>
      </main>
    </>
  );
}
